=== YashWalke/python3-mongo-template/configs/schemas/logging.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "version": {
            "type": "integer",
            "minimum": 1
        },
        "disable_existing_loggers": {
            "type": "boolean"
        },
        "formatters": {
            "type": "object",
            "properties": {
                "log": {
                    "type": "object",
                    "properties": {
                        "format": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "format"
                    ]
                }
            },
            "required": [
                "log"
            ]
        },
        "handlers": {
            "type": "object",
            "properties": {
                "file_handler": {
                    "type": "object",
                    "properties": {
                        "class": {
                            "type": "string"
                        },
                        "filename": {
                            "type": "string"
                        },
                        "when": {
                            "type": "string",
                            "enum": [
                                "midnight"
                            ]
                        },
                        "interval": {
                            "type": "integer",
                            "minimum": 1
                        },
                        "backupCount": {
                            "type": "integer",
                            "minimum": 1
                        },
                        "formatter": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "class",
                        "filename",
                        "when",
                        "interval",
                        "backupCount",
                        "formatter"
                    ]
                },
                "console": {
                    "type": "object",
                    "properties": {
                        "class": {
                            "type": "string"
                        },
                        "level": {
                            "type": "string",
                            "enum": [
                                "DEBUG"
                            ]
                        },
                        "formatter": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "class",
                        "level",
                        "formatter"
                    ]
                }
            },
            "required": [
                "file_handler",
                "console"
            ]
        },
        "loggers": {
            "type": "object",
            "properties": {
                "main": {
                    "type": "object",
                    "properties": {
                        "handlers": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "level": {
                            "type": "string",
                            "enum": [
                                "DEBUG"
                            ]
                        },
                        "propagate": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "handlers",
                        "level",
                        "propagate"
                    ]
                },
                "db": {
                    "type": "object",
                    "properties": {
                        "handlers": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "level": {
                            "type": "string",
                            "enum": [
                                "DEBUG"
                            ]
                        },
                        "propagate": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "handlers",
                        "level",
                        "propagate"
                    ]
                }
            },
            "required": [
                "main",
                "db"
            ]
        }
    },
    "required": [
        "version",
        "disable_existing_loggers",
        "formatters",
        "handlers",
        "loggers"
    ]
}

=== YashWalke/python3-mongo-template/configs/logging.json
{
    "version": 1,
    "disable_existing_loggers": false,
    "formatters": {
        "log": {
            "format": "%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s\t"
        }
    },
    "handlers": {
        "file_handler": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": "./logs/migrate_script_log.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
            "formatter": "log"
        },
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "log"
        }
    },
    "loggers": {
        "main": {
            "handlers": [
                "file_handler",
                "console"
            ],
            "level": "DEBUG",
            "propagate": false
        },
        "db": {
            "handlers": [
                "file_handler",
                "console"
            ],
            "level": "DEBUG",
            "propagate": false
        }
    }
}
